name: Cron contributter

on:
  schedule:
    - cron: "1 15 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MY_SCREEN_NAME: egpl0
      MY_LANGUAGE: ja
      CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
      CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_KEY }}
      ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
      TZ: 'Asia/Tokyo'
    steps:
      - name: Check date
        run: |
          date
      - name: Setup tweet.sh
        run: |
          sudo apt install nkf -y
          curl -s https://raw.githubusercontent.com/piroor/tweet.sh/trunk/tweet.sh > tweet.sh
          chmod +x tweet.sh
      - name: Setup contributter.sh
        run: |
          curl -s https://raw.githubusercontent.com/eggplants/contributter.sh/master/contributter > contributter.sh
          chmod +x contributter.sh
      - name: Post on Twitter
        run: |
          echo ${MY_SCREEN_NAME}
          ./tweet.sh post "$(./contributter.sh eggplants)"
