name: llvm Test

on:
  workflow_dispatch:
    inputs:
      llvm_version:
        description: 'building version of LLVM'
        required: true
        default: '11.0'

jobs:
  test:
    runs-on: ${{matrix.os}}
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        include:
          - build: linux-musl
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - build: mac
            os: macOS-latest
            target: x86_64-apple-darwin

    steps:
      - name: Checkout
        uses: actions/checkout@v1    
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "${{ github.event.inputs.llvm_version }}"
      - name: Check llvm
        run: |
          ls llvm
          llvm-config --version
