name: llvmenv

on:
  workflow_dispatch:
    inputs:
      llvm_version:
        description: 'building version of LLVM'
        required: true
        default: '12.0.0'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Check llvm
        run: |
          sudo apt install libunwind-dev
          cargo install --git https://github.com/llvmenv/llvmenv -q
          llvmenv init
          llvmenv build-entry "${{ github.event.inputs.llvm_version }}"
