name: mac test
on: [workflow_dispatch]
jobs:
  mac:
    runs-on: macOS-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@master

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        run: |
          brew install tcl-tk pyenv
          echo 'export PATH="/usr/local/opt/tcl-tk/bin:$PATH";"' >> ~/.bash_profile
          echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bash_profile
          echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bash_profile
          echo 'eval "$(pyenv init --path)"' >> ~/.bash_profile
          source ~/.bash_profile
          p="$(brew --prefix tcl-tk)"
          env \
            PATH="${p}/bin:$PATH" \
            LDFLAGS="-L${p}/lib" \
            CPPFLAGS="-I${p}/include" \
            PKG_CONFIG_PATH="${p}/lib/pkgconfig" \
            CFLAGS="-I${p}/include" \
            PYTHON_CONFIGURE_OPTS="--with-tcltk-includes='-I${p}/include' --with-tcltk-libs='-L${p}/lib -ltcl8.6 -ltk8.6'" \
            pyenv install ${{ env.PYTHON_VERSION }}
          pyenv global ${{ env.PYTHON_VERSION }}
          pyenv versions
          python -V
