name: mac test
on: [workflow_dispatch]
jobs:
  test:
    runs-on: macOS-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@master
        with:
          python-version: 3.9
      - name: test
        run: python -c "import tkinter;print(tkinter.Tcl().eval('info patchlevel'))"
