name: mac test
on: [workflow_dispatch]

env:
  PYTHON_VERSION: "3.9.7"

jobs:
  mac:
    runs-on: macOS-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v4

      - name: Install deps with brew
        run: |
          brew install python-tk@3.9 pyenv
          echo 'export PATH="/usr/local/opt/tcl-tk/bin:$PATH"' >> ~/.bash_profile
          echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bash_profile
          echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bash_profile
          echo 'eval "$(pyenv init --path)"' >> ~/.bash_profile
          source ~/.bash_profile

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        run: |
          p="$(brew --prefix tcl-tk)"
          env \
            PATH="${p}/bin:$PATH" \
            LDFLAGS="-L${p}/lib" \
            CPPFLAGS="-I${p}/include" \
            PKG_CONFIG_PATH="${p}/lib/pkgconfig" \
            CFLAGS="-I${p}/include" \
            PYTHON_CONFIGURE_OPTS="--with-tcltk-includes='-I${p}/include' --with-tcltk-libs='-L${p}/lib -ltcl8.6 -ltk8.6'" \
            pyenv install ${{ env.PYTHON_VERSION }}
          pyenv global ${{ env.PYTHON_VERSION }}

      - name: Check
        run: |
          pyenv versions
          echo -n 'py2:'
          python -V
          pip -V
          echo -n 'py3:'
          python3 -V
          pip3 -V
          echo 'tk:'
          python3 -c "import tkinter;print('tk:',tkinter.Tcl().eval('info patchlevel'))"
