name: mac test
on: [workflow_dispatch]

env:
  PYTHON_VERSION: "3.9.7"

jobs:
  mac:
    runs-on: macOS-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@master

      - name: Install deps with brew
        run: |
          brew install python-tk@3.9 pyenv

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check
        run: |
          echo -n 'py2:'
          python -V
          pip -V
          echo -n 'py3:'
          python3 -V
          pip3 -V
          echo 'tk:'
          python3 -c "import tkinter;print('tk:',tkinter.Tcl().eval('info patchlevel'))"
