name: mac test2
on: [workflow_dispatch]

env:
  PYTHON_VERSION: "3.9.7"

jobs:
  mac:
    runs-on: macOS-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3

      - name: Install deps with brew
        run: |
          brew install python-tk@3.9 pyenv

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check
        run: |
          python3 -V
          python3 -c "import tkinter;print('tk',tkinter.Tcl().eval('info patchlevel'))"
