name: Morning

on:
  schedule:
    - cron: "1 21 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MY_SCREEN_NAME: egpl0
      MY_LANGUAGE: ja
      TZ: 'Asia/Tokyo'
    steps:
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install shindan-cli
      - name: Check date
        run: |
          date
      - name: Get status
        id: tweet-status
        run: |
          echo "::set-output name=STATUS::$(shindan 1118916 eggplants -l -H)"
      - name: Tweet
        uses: snow-actions/tweet@v1.1.0
        env:
          CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          CONSUMER_API_SECRET_KEY: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_KEY }}
          ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        with:
          status: |
            ${{ steps.tweet-status.outputs.STATUS }}
