name: Build pdcurses

on: [workflow_dispatch, push]
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: DL
        run: |
          ls
          Invoke-WebRequest https://github.com/wmcbrine/PDCurses/archive/refs/heads/master.zip -OutFile master.zip
          Expand-Archive -Path master.zip
      - name: Make
        # shell: bash
        run: |
          ls
          cd master\PDCurses-master\wincon
          make -f Makefile WIDE=Y DLL=Y
      - name: Set PATH
        run: |
          ls
          echo "PATH=$PATH:C:\msys64\mingw64\bin" >> $GITHUB_ENV
      - name: Install
        run: |
          cd master\PDCurses-master\wincon
          mv pdcurses.a libpdcurses.a
          mv pdcurses.dll C:\msys64\mingw64\bin
          mv libpdcurses.a C:\msys64\mingw64\lib
          mv ..\curses.h C:\msys64\mingw64\include
          mv ..\panel.h C:\msys64\mingw64\include
      - name: Test
        run: |
          Invoke-WebRequest 'https://web.archive.org/web/20070220170601if_/http://www.tkl.iis.u-tokyo.ac.jp:80/~toyoda/sl/sl.tar' -OutFile sl.tar
          tar -xopf sl.tar
          cd sl
          Invoke-WebRequest 'https://web.archive.org/web/20090316133609/http://www.izumix.org.uk:80/sl/sl5-1.patch' -OutFile sl5-1.patch
          git apply -p1 sl5-1.patch
          (Get-Content -path sl.c -Raw) -replace "ncurses/","" | Out-File _
          rm sl.c
          mv _ sl.c
          ls
          make
          mv sl sl-h
          ls
