name: Build pdcurses

on: [workflow_dispatch, push]
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: DL
        run: |
          ls
          Invoke-WebRequest https://github.com/wmcbrine/PDCurses/archive/refs/heads/master.zip -OutFile master.zip
          Expand-Archive -Path master.zip
      - name: Make
        shell: bash
        run: |
          ls
          cd master/PDCurses-master/wincon
          make -f Makefile WIDE=Y DLL=Y
      - name: Set PATH
        run: |
          ls
          echo "PATH=$PATH:C:\msys64\mingw64\bin" >> $GITHUB_ENV
      - name: Install
        run: |
          cd master\PDCurses-master\wincon
          mv pdcurses.a libcurses.a
          mv pdcurses.dll C:\msys64\mingw64\bin
          mv libpdcurses.a C:\msys64\mingw64\lib
          mv ..\curses.h ..\panel.h C:\msys64\mingw64\include
          
