name: Build pdcurses

on: [workflow_dispatch, push]
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install - pdcurse
        run: |
          Invoke-WebRequest https://github.com/wmcbrine/PDCurses/archive/refs/heads/master.zip -OutFile master.zip
          Expand-Archive -Path master.zip
          
          cd master\PDCurses-master\wincon
          make -f Makefile WIDE=Y DLL=Y UTF8=Y
          
          New-Item C:\ncurses -ItemType Directory
          New-Item C:\ncurses\bin -ItemType Directory
          New-Item C:\ncurses\lib -ItemType Directory
          New-Item C:\ncurses\include -ItemType Directory
          mv pdcurses.a libpdcurses.a
          mv pdcurses.dll C:\ncurses\bin
          mv libpdcurses.a C:\ncurses\lib
          mv ..\curses.h C:\ncurses\include
          mv ..\panel.h C:\ncurses\include

          ls C:\ncurses
          ls C:\ncurses\include
          ls C:\ncurses\lib

      - name: Install - termcap
        run: |
          Invoke-WebRequest https://jaist.dl.sourceforge.net/project/gnuwin32/termcap/1.3.1/termcap-1.3.1-bin.zip -OutFile termcap-bin.zip
          Expand-Archive -Path termcap-bin.zip
          Invoke-WebRequest https://jaist.dl.sourceforge.net/project/gnuwin32/termcap/1.3.1/termcap-1.3.1-lib.zip -OutFile termcap-lib.zip
          Expand-Archive -Path termcap-lib.zip
          New-Item C:\termcap -ItemType Directory
          Move-Item -Path termcap-bin\bin -Destination C:\termcap -force
          Move-Item -Path termcap-lib\lib -Destination C:\termcap -force
          Move-Item -Path termcap-lib\include -Destination C:\termcap -force

          ls C:\termcap
          ls C:\termcap\include
          ls C:\termcap\lib

      - name: Test - dl
        run: |
          Invoke-WebRequest 'https://github.com/eggplants/sl-h_binary/blob/master/sl-h.zip?raw=true' -OutFile sl-h.zip
          Expand-Archive -Path sl-h.zip

      - name: Test - make
        shell: bash
        run: |
          cd sl-h/sl-h
          gcc sl.c -Wall -O2 -o sl -lpdcurses -ltermcap \
                   -I C:\\ncurses\\include -I C:\\termcap\\include \
                   -L C:\\ncurses\\lib -L C:\\termcap\\lib -DLINUX20
          mv sl sl-h
          ls -lah
