name: Build pdcurses

on: [workflow_dispatch, push]
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: DL
        run: |
          Invoke-WebRequest https://github.com/wmcbrine/PDCurses/archive/refs/heads/master.zip -OutFile master.zip
          Expand-Archive -Path master.zip
      - name: Make
        run: |
          cd master\PDCurses-master\wincon
          make -f Makefile WIDE=Y DLL=Y UTF8=Y
      - name: Install
        run: |
          New-Item C:\ncurses -ItemType Directory
          New-Item C:\ncurses\bin -ItemType Directory
          New-Item C:\ncurses\lib -ItemType Directory
          New-Item C:\ncurses\include -ItemType Directory
          cd master\PDCurses-master\wincon
          mv pdcurses.a libpdcurses.a
          mv pdcurses.dll C:\ncurses\bin
          mv libpdcurses.a C:\ncurses\lib
          mv ..\curses.h C:\ncurses\include
          mv ..\panel.h C:\ncurses\include
      - name: Test - dl
        run: |
          Invoke-WebRequest 'https://github.com/eggplants/sl-h_binary/blob/master/sl-h.zip?raw=true' -OutFile sl-h.zip
          Expand-Archive -Path sl-h.zip
      - name: Test - make
        shell: bash
        run: |
          cd sl-h/sl-h
          sed -i 's/lncurses/lpdcurses -I C:\\ncurses\\include -L C:\\ncurses\\lib /' Makefile
          make
          mv sl sl-h
