name: Revive

on:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Configure git
      run: |
        echo "https://${GITHUB_ACTOR}"
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git remote set-url origin "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}"
        git checkout "${GITHUB_REF##*/}"
    - name: Update log
      run: |
        date >> update.log
    - name: Commit
      run: |
        git add .
        git commit -m "Update: $(date +%y%m%d)"
        git push origin "${GITHUB_REF##*/}"
