name: Build sl-h on windows

on: [workflow_dispatch, push]
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install - pdcurse
        run: |
          Invoke-WebRequest https://github.com/wmcbrine/PDCurses/archive/refs/heads/master.zip -OutFile master.zip
          Expand-Archive -Path master.zip
          
          cd master\PDCurses-master\wincon
          $data=Get-Content Makefile | % { $_ -replace "-O2 -Wall","-O2 -Wall -m32" }
          $data | Out-File Makefile -Encoding UTF8
          make -f Makefile WIDE=Y DLL=Y UTF8=Y
          
          New-Item C:\ncurses -ItemType Directory
          New-Item C:\ncurses\bin -ItemType Directory
          New-Item C:\ncurses\lib -ItemType Directory
          New-Item C:\ncurses\include -ItemType Directory
          mv pdcurses.a libpdcurses.a
          mv pdcurses.dll C:\ncurses\bin
          mv libpdcurses.a C:\ncurses\lib
          mv ..\curses.h C:\ncurses\include
          mv ..\panel.h C:\ncurses\include

          ls C:\ncurses
          ls C:\ncurses\include
          ls C:\ncurses\lib

      - name: DL - termcap
        run: |
          Invoke-WebRequest https://ftp.gnu.org/gnu/termcap/termcap-1.3.1.tar.gz -OutFile termcap.tar.gz
          tar -xvzf termcap.tar.gz

      - name: Build - termcap
        shell: bash
        run: |
          cd termcap-1.3.1
          ./configure
          make

      - name: DL - termcap
        run: |
          New-Item C:\termcap -ItemType Directory
          # New-Item C:\termcap\bin -ItemType Directory
          New-Item C:\termcap\lib -ItemType Directory
          New-Item C:\termcap\include -ItemType Directory

          cd termcap-1.3.1
          mv termcap.h C:\termcap\include
          mv termcap.o C:\termcap\lib
          mv tparam.o C:\termcap\lib
          mv version.o C:\termcap\lib
          mv termcap.a C:\termcap\lib

      - name: Test - dl
        run: |
          Invoke-WebRequest 'https://github.com/eggplants/sl-h_binary/blob/master/sl-h.zip?raw=true' -OutFile sl-h.zip
          Expand-Archive -Path sl-h.zip

      - name: Test - make
        shell: bash
        run: |
          cd sl-h/sl-h
          gcc sl.c -Wall -O2 -m32 \
                   -o sl -lpdcurses -ltermcap \
                   -I C:\\ncurses\\include -I C:\\termcap\\include \
                   -L C:\\ncurses\\lib -L C:\\termcap\\lib -DLINUX20
          mv sl sl-h
          ls -lah
