name: Build termcap on Windows

on: [workflow_dispatch, push]
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: DL
        run: |
          Invoke-WebRequest https://ftp.gnu.org/gnu/termcap/termcap-1.3.1.tar.gz -OutFile termcap.tar.gz
          tar -xvzf termcap.tar.gz

      - name: Install
        shell: bash
        run: |
          cd termcap-1.3.1
          ./configure
          make
