name: Check gh_token

on:
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Check
        run: |
          python -c 'import os,pprint
          [pprint.pprint(i)for i in os.environ.items()]'
        env:
          github_token_: ${{ secrets.GH_ADMIN_TOKEN }}
