name: Check if TZ works
on: workflow_dispatch # [push, pull_request]
jobs:
  check-date:
    env:
      TZ: 'Asia/Tokyo'
    runs-on: ubuntu-latest
    steps:
      - run: date
  check-date-each:
    runs-on: ubuntu-latest
    steps:
      - run: date
      - run: date
        env:
          TZ: 'Asia/Tokyo'
